### ISSUE TITLE
cannot open the MediaCreationTool.bat

### ISSUE THREAD

**Issue by MatrixxZENG** [AveYo/MediaCreationTool.bat#41] opened 2021-11-11 06:34 UTC
Thanks for the author!
but I have some problem in running this bat.
Neither I double click or run as Admin, the cmd window just show and auto close immediately.
Should I install something like net.framework before running this?

**Comment by AveYo** [comment] 2021-11-11 12:20
script should launch fine on a default windows 7 and up  

your os might be chopped of / crippled, in which case I suggest a repair (in-place) install
**or**,
you've copy-pasted the script incorrectly, in which case you should just use the github button at top right Code - Download ZIP

**Comment by AveYo** [comment] 2021-11-11 12:21
at a minimum, the script requires powershell 2.0  (net framework 2.0 or higher)

**Comment by gerardog** [comment] 2021-11-11 14:36
Also happening to me on W10 21H1.
renamed to "auto MediaCreationTool.bat" and now getting:

```
 Windows 11 Version  21H2  22000.258.211007-1642.co_release_svc_refresh  en-US  Consumer  x64

https://software-download.microsoft.com/download/pr/888969d5-f34g-4e03-ac9d-1f9786c69161/MediaCreationToolW11.exe
https://download.microsoft.com/download/5/1/f/51fdebf9-89b1-4a87-92cd-0ea73e290c5c/products_20211019.cab

 ERROR  Check urls in browser | del MCT dir | use powershell v3.0+ | unblock powershell | enable BITS serv
Press any key to continue . . .
```

**Comment by AveYo** [comment] 2021-11-11 14:55
what antivirus are you using? it might inadvertently block downloading methods via powershell
what language is your os in? 

if you copy-paste-enter this into powershell, does it creates a `MCT11.exe` file in your `Downloads` folder?
``` ps1
write-host;
function DOWNLOAD ($u, $f, $p = $env:__CD__) {
  Import-Module BitsTransfer; $wc = new-object Net.WebClient; $wc.Headers.Add('user-agent','ipad') 
  $n = $u.split('/')[-1]; $s = 'https://'; $i = 'http://'; $d = $u.replace($s,'').replace($i,''); $https = $s+$d; $http = $i+$d 
  $file = join-path $p $f; $alt = join-path $p $n
  foreach ($url in $http, $https) { 
    if (([IO.FileInfo]$file).Exists) {return}; try {Start-BitsTransfer $url $file -ea 1} catch {}
    if (([IO.FileInfo]$file).Exists) {return}; try {$wc.DownloadFile($url, $file)} catch {}
    if (([IO.FileInfo]$file).Exists) {return}; try {certutil -URLCache -split -f $url >''; ren $alt $f -force -ea 0} catch {}
    if (([IO.FileInfo]$file).Exists) {return}; write-host -fore Yellow " $f download failed "
} }
pushd ((new-object -ComObject Shell.Application).NameSpace('shell:Downloads').Self.Path) 
DOWNLOAD 'https://software-download.microsoft.com/download/pr/888969d5-f34g-4e03-ac9d-1f9786c69161/MediaCreationToolW11.exe' 'MCT11.exe'
write-host;
```

**Comment by gerardog** [comment] 2021-11-11 15:40
Yes, the script downloads MCT.exe (but placed it in my home dir).

![image](https://user-images.githubusercontent.com/3901474/141325515-aaf42971-7d62-4629-b785-464af4957a86.png)

I was using Windows Defender. Now it is disabled and still see the same behavior.
When running 'auto MediaCreationTool.bat', both MediaCreationToolW11.exe and products_20211019.cab are downloaded correctly in Downloads\MCT.

I wonder if this can be related to #29 download validation issues.

**Comment by MatrixxZENG** [comment] 2021-11-11 15:50
> at a minimum, the script requires powershell 2.0 (net framework 2.0 or higher)

I download the full zip to find the problems.
but i have downloaded the history version, which can running success. 
thx for replying.

**Comment by AveYo** [comment] 2021-11-15 21:45
is this still an issue with the last update?

**Comment by MatrixxZENG** [comment] 2021-11-16 01:09
> is this still an issue with the last update?
yes, I downloaded the latest version 2min ago.
it's still an issue...

**Comment by Sanjana-tl** [comment] 2021-11-22 08:28
The urls are fine on a browser. Have Windows Powershell 5, Pwsh 7.1.3, and BITS service by default (manual start). Also ran unblock-file on the bat file.

**Comment by AveYo** [comment] 2021-11-22 17:12
@Sanjana-tl, what exactly happens in your case? 
How far does it go, where does it stop, can you screenshot the specific moment?

**Comment by gerardog** [comment] 2021-11-23 18:29
In mi case, I was expecting a choice menu, but nothing appears. Then jumps to 
Tried using "11 iso" or other arguments, and still same problem.

https://user-images.githubusercontent.com/3901474/143082799-963c2ce0-4693-42d9-8f91-8eb1984a2a00.mp4

**Comment by gerardog** [comment] 2021-12-04 22:37
@AveYo Shouldn't this menu appear?

![image](https://user-images.githubusercontent.com/3901474/144726606-12f2c4a0-cdc7-44c1-be79-765e3d3c4f55.png)

Why wouldn't it show up in my W10/W11 default english install ?

**Comment by AveYo** [comment] 2021-12-07 10:30
it should. I have no idea 🔢

**Comment by jim26061** [comment] 2021-12-07 21:08
СПАСИБО !!!

**Comment by filos1983** [comment] 2022-01-11 11:13
Hello, thanks for your script! I'm trying to use it in my environment but i receive an error (screenshot linked below).
I checked the listed possible issue but everything seems fine:

- If i try to download those files pasting URLs in browser it works
- MCT directory has been deleted after the previous failed attempts
- Powershell version is 5.1
- Powershell seems unblocked but maybe there's something I don't know about it
- BITS service is running
- Antivirus is kasperski but now is disabled and it doesn't list anything

https://ibb.co/PwTCbQt

Do you have any idea about what is not working?

Thanks

**Comment by ChaosDMNS** [comment] 2022-02-03 02:28
was a little confusing for a while to figure out how to use the script..
But I figured atleast enough out to rename it to "auto 11 Pro MediaCreationTool.bat" and ran it as Admin....

THANK YOU THANK YOU THANK YOU..... Win11 is up and running and it's basicly flying... and here I was worried it would lag or crash or something.. works like a dream.. THANK YOU...

**Comment by AveYo** [comment] 2022-03-16 23:01
While I did close this issue 13 days ago, it still has been bugging me to no end.

I have decided to rework the script in order to prevent issues stemming from non-canonical paths i.e. with special characters and accents that ntfs allows, but are particularly bad for scripts.
Specially when elevation is involved (when even windows itself has troubles handling it).

The updated script I just pushed should work around most issues I've managed to reproduce,
Now `C:\ESD` is always used as a work folder, and the original script path is preserved
and used when needing to create an iso.

Hopefully this done it for you too @MatrixxZENG @gerardog @Sanjana-tl @filos1983

**Comment by gerardog** [comment] 2022-03-17 00:56
Thanks @AveYo !
Tried latest. Still same issue.

Do I need to install something?
I've never seen this menus (as shown in the readme):

![image](https://user-images.githubusercontent.com/3901474/158714655-dbb56538-141c-4cf6-83fc-973f07af12e1.png)

Instead, when I run MediaCreationTool.bat (as admin) I see this screen appear for half a second:
![image](https://user-images.githubusercontent.com/3901474/158714831-21d75709-9b50-40bb-8534-f6a693c19827.png)

Then it closes, and this other one appears:

![image](https://user-images.githubusercontent.com/3901474/158714866-b377c6f9-4633-4558-b351-1fe1d8095507.png)

I was expecting that a menu should appear.

If I try renaming to auto, or calling `MediaCreationTool.bat auto` then the same occurs.

I think some inner script is failing to start. I used english (US) windows 10 with spanish language pack. But now upgraded to 11. Still same exact problem.

Tried to debug your script (the previous version) but it was quite difficult to follow. If you add a bunch of debug traces I can help you see where it is failing. I'll be very glad to help

Or else, maybe you could get a clean windows 11 (or 10) virtual machine and just download and run the .BAT file.? I think it will fail too. 

Thanks!

**Comment by AveYo** [comment] 2022-03-17 03:41
Nope, it just works for me and many others, on multiple languages and windows versions 7, 8, 10, 11, 11 Dev, clean installed or otherwise.

Not that it matters, but you don't need to run the script as admin, it elevates itself.

**Have you tried a clean install / vm?**
Because I can't reproduce it no matter what.
The powershell part does not run at all for you.
Guess I will make a special version for you to see what does not work.

**Comment by gerardog** [comment] 2022-03-18 03:02
> Still curious about your non-working environment.

Windows 11 - Professional (english + spanish language pack) 

> Can you open a non-admin command prompt and enter:
powershell -nop -c start -verb runas cmd \"/k echo;$PID\"

<img width="534" alt="image" src="https://user-images.githubusercontent.com/3901474/158880159-52af3eed-505c-4563-9322-18a77bf63920.png">

`some.bat` fails: (no Windows.Form displayed)
<img width="248" alt="image" src="https://user-images.githubusercontent.com/3901474/158880436-69b21d44-c60a-4e87-8e39-c3ce026af0ca.png">

Pure powershell works:
<img width="932" alt="image" src="https://user-images.githubusercontent.com/3901474/158880609-b0134f6e-df96-4b12-9dea-b7da4fc8942e.png">

rewrote `some.bat` from scratch: it works!

```
@echo on
set p1=CHOICES VAR "one,two,three"

FOR /F "delims=" %%I in ('Powershell -c "([io.file]::ReadAllText(\"%~f0\") -split (\"#\:CHOICES:\"))[1] | iex ; iex $env:p1"') do set c=%%I 

exit /b

#:CHOICES:#
function CHOICES ($index,$choices,$def=1,$title='Choices',[int]$sz=12,$bc='MidnightBlue',$fc='Snow',[string]$win='300') {
 [void][Reflection.Assembly]::LoadWithPartialName('System.Windows.Forms'); $f=new-object Windows.Forms.Form; $global:ret=''
 $bt=@(); $i=1; $ch=($choices+',Cancel').split(','); $ch |foreach {$b=New-Object Windows.Forms.Button; $b.Font='Consolas,'+$sz
 $b.Name=$i; $b.Text=$_;  $b.Margin='0,0,9,9'; $b.Location='9,'+($sz*3*$i-$sz); $b.MinimumSize=$win+',18'; $b.AutoSize=1
 $b.add_GotFocus({$this.BackColor=$fc; $this.ForeColor=$bc}); $b.add_LostFocus({$this.BackColor=$bc; $this.ForeColor=$fc})
 $b.FlatStyle=0; $b.Cursor='Hand'; $b.add_Click({$global:ret=$this.Name;$f.Close()}); $f.Controls.Add($b); $bt+=$b; $i++}
 $f.Text=$title; $f.BackColor=$bc; $f.ForeColor=$fc; $f.StartPosition=4; $f.AutoSize=1; $f.AutoSizeMode=0; $f.MaximizeBox=0
 $f.AcceptButton=$bt[$def-1]; $f.CancelButton=$bt[-1]; $f.Add_Shown({$f.Activate();$bt[$def-1].focus()})
 $f.ShowDialog() >''; $index=$global:ret; if ($index -eq $ch.length) {return 0} else {return $index}
} 
#:CHOICES:#  gui dialog with inverted focus returning selected index - lean and mean snippet by AveYo, 2018 - 2021
```

<img width="852" alt="image" src="https://user-images.githubusercontent.com/3901474/158919167-31a8da5f-8b63-4e8d-b9f5-6e04370b3ad6.png">

Until I realize I forgot `-NoProfile`.... and now it doesnt work anymore. WTF?

Not sure what's happening but if looks like if you initialize the console (something my profile probably does) by adding something like `echo $null;` at startup, then your code works... So your fixed `Some.bat` is:

```
@echo off

set _ #=echo $null;$f0=[io.file]::ReadAllText($env:0); $0=($f0-split '#\:CHOICES\:' ,3)[1]; $1=$env:1-replace'([`@$])','`$1'; iex($0+$1)
(...)
```

**Comment by AveYo** [comment] 2022-03-18 10:35
This is the very first time I see -noprofile causing issues instead of solving them!
Certainly non-standard behavior.
Can you open powershell, as both standard and as admin and enter:
```ps1
$pro='AllUsersAllHosts','AllUsersCurrentHost','CurrentUserAllHosts','CurrentUserCurrentHost'
foreach ($f in $pro) {$fn=$profile.$f; $fn; if (test-path $fn) {gc $fn}}
```
Note that I'm interested in the handling of the snippet as well, so is this working:
```bat
@echo off

set ^ #=$f0=[io.file]::ReadAllText($env:0); $0=($f0-split '#\:CHOICES\:' ,3)[1]; $1=$env:1-replace'([`@$])','`$1'; iex($0+$1)
set ^ #=&set "0=%~f0"& set 1=;CHOICES VAR "one,two,three" 2& (for /f %%x in ('powershell -c "%#%"') do set "C=%%x")

echo choice: %C% 
pause
exit /b

#:CHOICES:#
function CHOICES ($index,$choices,$def=1,$title='Choices',[int]$sz=12,$bc='MidnightBlue',$fc='Snow',[string]$win='300') {
 [void][Reflection.Assembly]::LoadWithPartialName('System.Windows.Forms'); $f=new-object Windows.Forms.Form; $global:ret=''
 $bt=@(); $i=1; $ch=($choices+',Cancel').split(','); $ch |foreach {$b=New-Object Windows.Forms.Button; $b.Font='Consolas,'+$sz
 $b.Name=$i; $b.Text=$_;  $b.Margin='0,0,9,9'; $b.Location='9,'+($sz*3*$i-$sz); $b.MinimumSize=$win+',18'; $b.AutoSize=1
 $b.add_GotFocus({$this.BackColor=$fc; $this.ForeColor=$bc}); $b.add_LostFocus({$this.BackColor=$bc; $this.ForeColor=$fc})
 $b.FlatStyle=0; $b.Cursor='Hand'; $b.add_Click({$global:ret=$this.Name;$f.Close()}); $f.Controls.Add($b); $bt+=$b; $i++}
 $f.Text=$title; $f.BackColor=$bc; $f.ForeColor=$fc; $f.StartPosition=4; $f.AutoSize=1; $f.AutoSizeMode=0; $f.MaximizeBox=0
 $f.AcceptButton=$bt[$def-1]; $f.CancelButton=$bt[-1]; $f.Add_Shown({$f.Activate();$bt[$def-1].focus()})
 $f.ShowDialog() ; $index=$global:ret; if ($index -eq $ch.length) {return 0} else {return $index}
} #:CHOICES:#  gui dialog with inverted focus returning selected index - lean and mean snippet by AveYo, 2018 - 2021
```
Anyway, great job so far on tracing it!

**Comment by gerardog** [comment] 2022-03-19 02:43
What is inside my profile is not the problem... this fails with -noprofile which should be not loading any of those 4 files, right?
Just in case. I deleted all 4 files. Issue persisted.

I created an issue for microsoft, just to shame myself... 
Because I found that I have a broken `Invoke-Expression.ps1` in the PATH.

In case you want to see how it ends... See issue 17031 at PowerShell/PowerShell

When I fixed/deleted that .ps1 file, your original MediaCreationTool.bat worked.

**Comment by AveYo** [comment] 2022-03-19 05:09
Well I knew it's something on your end!
The script works for so many people as-is.
But I still wanted to help and make a workaround 
_(would not be the first time I break the script trying to fix stuff like this)_

It's something to keep in mind
-noprofile does help with many things, but not with a core cmdlet being hijacked locally ;)
I've got bitten once by local profile file, and I said never again!

Mean time I have updated the script with hopefully other fixes
Anyway, I

**Closed** 2022-03-20 15:31 UTC

**Comment by YourPainIsMyPleasure** [comment] 2023-07-24 12:44
USE VPN ;)

**Comment by gggggggggg4** [comment] 2023-11-20 09:59
![изображение_2023-11-20_165907332](https://github.com/AveYo/MediaCreationTool.bat/assets/151519393/afe1d5af-a00b-472c-aa36-de03d9548d99)
what to do in this situation?

**Comment by aibek12312** [comment] 2024-03-07 14:00
**what vpn?**
